Update tests
* lispy-test.el (lispy-ace-subword): Unite two tests with identical
name (caused to fail tests).
(lispy-outline-add): Update test to agree with current behaviour of
lispy-meta-return (since 6efe2b4e).
(lispy-tilde): Rename second instance of lispy-outline-add to avoid
two identical test names.
(lispy--pretty-args): Agree with updated docstring of defun (since
Emacs 73e75e18).

ERT fails with redefined tests in batch mode:
    Error: error ("Test ‘lispy-ace-subword’ redefined")